# Generated by Django 4.1.7 on 2023-12-12 14:15

from django.db import migrations, models
import search_service.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(upload_to=search_service.models.image_path)),
            ],
        ),
    ]
